export const SEVERITY_KEYWORDS = {
  HIGH: [
    "fire",
    "burn",
    "burning",
    "flame",
    "flames",
    "inferno",
    "wildfire",
    "house fire",
    "building fire",
    "forest fire",
    "grass fire",
    "electrical fire",
    "chemical fire",
    "vehicle fire",
    "smoke",
    "thick smoke",
    "black smoke",
    "sparks",
    "embers",
    "explosion",
    "blast",
    "bomb",
    "grenade",
    "firecracker",
    "gunshot",
    "shooting",
    "active shooter",
    "rifle",
    "shotgun",
    "pistol",
    "revolver",
    "firearm",
    "bullet",
    "ammunition",
    "hostage",
    "kidnap",
    "abduction",
    "terror",
    "terrorist",
    "assault",
    "attack",
    "armed",
    "knife",
    "stabbing",
    "stabbed",
    "slashing",
    "murder",
    "homicide",
    "dead body",
    "corpse",
    "lifeless",
    "fatal",
    "fatality",
    "critical",
    "emergency",
    "help",
    "rescue",
    "trapped",
    "collapse",
    "collapsed",
    "building collapse",
    "bridge collapse",
    "landslide",
    "rockslide",
    "sinkhole",
    "earthquake",
    "quake",
    "aftershock",
    "tsunami",
    "storm surge",
    "typhoon",
    "tornado",
    "cyclone",
    "hurricane",
    "lightning strike",
    "electrocution",
    "live wire",
    "high voltage",
    "gas leak",
    "gas explosion",
    "chemical leak",
    "toxic gas",
    "hazardous",
    "hazmat",
    "poison",
    "poisoning",
    "carbon monoxide",
    "radiation",
    "biohazard",
    "pandemic",
    "outbreak",
    "infected",
    "mass casualty",
    "severe injury",
    "bleeding",
    "unconscious",
    "not breathing",
    "person down",
    "person lying",
    "lying on ground",
    "collapsed person",
    "unresponsive",
    "person unresponsive",
    "fallen down",
    "down on ground",
    "medical emergency",
    "emergency on ground",
    "heart attack",
    "stroke",
    "seizure",
    "drowning",
    "near drowning",
    "suicide attempt",
    "jumping",
    "missing child",
    "missing person",
    "robbery",
    "armed robbery",
    "carjacking",
    "rape",
    "sexual assault",
    "domestic violence",
    "riot",
    "civil unrest",
    "hostile",
    "danger",
    "dangerous",
    "unsafe",
    "evacuate",
    "evacuation",
    "911",
    "ambulance",
    "fire truck",
    "police emergency",
    "bumbero",
    "sunog",
    "nasusunog",
    "nagadilaab",
    "kalayo",
    "apoy",
    "aso",
    "pagsabog",
    "baril",
    "binaril",
    "putukan",
    "patay",
    "patyon",
    "patyonon",
    "ginbuno",
    "ginlabo",
    "dugo",
    "kritikal",
    "emergency",
    "tabang",
    "bulig",
    "rescue",
    "dukot",
    "nadakpan",
    "nahulog",
    "natumba",
    "natrap",
    "nakulong",
    "guba",
    "naguba",
    "guho",
    "linog",
    "bagyo",
    "baha nga grabe",
    "landslide",
    "kidlat",
    "kuryente",
    "nakuryente",
    "makamatay",
    "delikado",
    "delikado gid",
    "ginatulod",
    "ginasunog",
    "ginpangawat",
    "holdup",
    "tulis",
    "nakawan",
    "krimen",
    "pulis",
    "sunog gid",
    "nagakalayo",
    "nagasinggit",
    "tabangi",
    "buligi",
    "ambulansya",
    "inaway",
    "ilinaway",
  ],

  MODERATE: [
    "flood",
    "flooding",
    "flash flood",
    "waist deep",
    "knee deep",
    "overflow",
    "overflowing",
    "water level",
    "water rise",
    "mud",
    "muddy",
    "road damage",
    "bridge damage",
    "road crack",
    "crack",
    "fallen tree",
    "tree branch",
    "obstruction",
    "blocked road",
    "traffic",
    "traffic jam",
    "vehicle accident",
    "collision",
    "crash",
    "minor crash",
    "motorcycle accident",
    "car accident",
    "truck accident",
    "oil spill",
    "fuel spill",
    "chemical spill",
    "water leak",
    "pipe leak",
    "burst pipe",
    "drain clog",
    "blocked drainage",
    "garbage clog",
    "power outage",
    "brownout",
    "blackout",
    "electric outage",
    "transformer",
    "transformer explosion",
    "streetlight",
    "street light",
    "broken light",
    "damaged pole",
    "electric pole",
    "wire hanging",
    "loose wire",
    "damaged cable",
    "internet outage",
    "phone outage",
    "fallen sign",
    "damaged roof",
    "roof leak",
    "window broken",
    "glass shattered",
    "fence damaged",
    "bridge crack",
    "erosion",
    "sink",
    "road sink",
    "animal attack",
    "stray dog",
    "snake",
    "monitor lizard",
    "wild animal",
    "crime report",
    "theft",
    "burglary",
    "vandalism",
    "illegal parking",
    "parking violation",
    "noise complaint",
    "loud music",
    "disturbance",
    "smoke smell",
    "strange odor",
    "foul smell",
    "baha",
    "tubig",
    "tubigan",
    "nagabaha",
    "nagataas tubig",
    "lubog",
    "tubog",
    "nagatulo",
    "tulo",
    "bara",
    "barado",
    "drain",
    "kanal",
    "sapa",
    "suba",
    "nagatrapik",
    "trapiko",
    "aksidente",
    "bangga",
    "salpukan",
    "nabunggo",
    "gasgas",
    "sira",
    "guba",
    "naguba",
    "bitak",
    "lubak",
    "poste",
    "kuryente",
    "brownout",
    "walang ilaw",
    "walang kuryente",
    "poste nga natumba",
    "natumba",
    "kahoy",
    "natumbang kahoy",
    "ulan",
    "kusog ulan",
    "hangin",
    "bagyo",
    "signal number",
    "warning",
    "evacuation center",
    "relief",
    "rescue team",
    "barangay response"
  ],

  LOW: [
    "garbage",
    "trash",
    "litter",
    "waste",
    "plastic",
    "bottle",
    "can",
    "paper",
    "dirty",
    "unclean",
    "cleaning",
    "sweep",
    "maintenance",
    "repair",
    "repaint",
    "paint",
    "graffiti",
    "wall writing",
    "sticker",
    "poster",
    "broken bench",
    "broken chair",
    "park maintenance",
    "playground",
    "sidewalk",
    "cracked sidewalk",
    "small pothole",
    "pothole",
    "grass",
    "overgrown",
    "weeds",
    "tree trimming",
    "branch trimming",
    "drain cleaning",
    "street cleaning",
    "clogged bin",
    "overflowing trash",
    "garbage collection",
    "missed pickup",
    "streetlight request",
    "dim light",
    "flickering light",
    "sign repair",
    "road marking",
    "crosswalk",
    "painting request",
    "beautification",
    "landscaping",
    "minor leak",
    "small crack",
    "maintenance request",
    "inspection",
    "routine check",
    "cleanup",
    "noise",
    "karaoke",
    "videoke",
    "loud speaker",
    "pet complaint",
    "stray cat",
    "stray dog",
    "mosquito",
    "pest",
    "rats",
    "cockroach",
    "flies",
    "basura",
    "kalat",
    "hugaw",
    "mahigko",
    "limpyo",
    "paglimpyo",
    "pagpanglimpyo",
    "silhig",
    "walis",
    "maintenance",
    "ayo",
    "ayuhon",
    "tambal",
    "repair",
    "kulayan",
    "pintura",
    "guhit",
    "drawing",
    "poster",
    "tarpaulin",
    "gamay nga baha",
    "gamay nga tulo",
    "lubak",
    "gamay nga bitak",
    "dalan",
    "karsada",
    "bangko",
    "parke",
    "tanom",
    "damo",
    "sagbot",
    "kahoy",
    "putol sanga",
    "kanal",
    "hugaw nga kanal",
    "ingay",
    "maingay",
    "videoke",
    "karaoke",
    "iro",
    "ido",
    "kuring",
    "iring",
    "lamok",
    "ilaga",
    "uk-ok",
    "langaw",
    "bulak",
    "garden",
    "flowers",
    "maintenance only"
  ],
} as const;

export type SeverityLevel = 'HIGH' | 'MODERATE' | 'LOW';

export const SEVERITY_DESCRIPTIONS = {
  HIGH: 'Immediate danger requiring emergency response',
  MODERATE: 'Significant issues requiring attention',
  LOW: 'Minor issues or maintenance requests',
} as const;